"""empty message

Revision ID: 97aa952f3eba
Revises: c33b0b9346e2
Create Date: 2019-05-19 16:13:02.626614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97aa952f3eba'
down_revision = 'c33b0b9346e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('api_token', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'user', ['api_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'api_token')
    # ### end Alembic commands ###
