"""empty message

Revision ID: c33b0b9346e2
Revises: 585ee9243e7b
Create Date: 2019-05-16 01:53:55.669976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c33b0b9346e2'
down_revision = '585ee9243e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registered_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_registered_at'), 'user', ['registered_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_registered_at'), table_name='user')
    op.drop_column('user', 'registered_at')
    # ### end Alembic commands ###
